### ISSUE TITLE
CI/CD Pipeline

### ISSUE THREAD

**Issue by amtjitro** [cse110-sp23-group25/tarot-cards#4]
# Task
Research CI/CD and github actions. Create `yaml` files to run the github actions and test on sample code before adding to repos.

# Due Date
Checkpoint 1 - Sunday, May 21st

# Deliverables

- [x] phase1.png - a diagram of your phase 1 build pipeline (can be phase1.drawio.png if using draw.io)
- [x] phase1.md - a short 2 page (roughly) status on the pipeline in terms of what is currently functional (and what is planned or in progress). Embed your diagram in the markdown file.
- [x] phase1.mp4 - a no more than 2 min video demonstration of the pipeline
